### ISSUE TITLE
Error 401 - Authorization header is not passed in the redirected url after upgrading Chrome to version 119

### ISSUE THREAD

**Issue by laurent-inqom** [requestly/requestly#1208]
### Describe your issue?

`Authorization` header disapear from request headers when using replace string http rules. We identified that this issue happens after Chrome upgrade from 118 to 119 version. The http 'replace string' rules are used to redirect from my dev server to my localhost. We found a workaround that is using edge, but someone in the team has edge on version 119 and has the problem with Authorization header disapearing.

### Repro steps
1. Open the Requestly app.
2. Create redirect rule (with a replace string rule).
3. Use any http request with an authorization header that will trigger the replace string rule
4. The Authorization header has vanished (resulting in 401 error for us).

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Chrome (version 119) on Windows

### Requestly Version

23.10.22

### Error case, executed on chrome v119.0.6045.106
![image](https://github.com/requestly/requestly/assets/120636893/2f241b99-2d4a-4bbd-a752-755266172901)
![image](https://github.com/requestly/requestly/assets/120636893/3b064640-4e66-45fa-9f55-90e70506804d)

### Ok case, on Edge v116.0.1938.69
![image](https://github.com/requestly/requestly/assets/120636893/2f0b5ab1-9170-4cf1-9b50-57e99b06ba3e)
![image](https://github.com/requestly/requestly/assets/120636893/77cab9cc-f9c2-47ba-b962-44e31b6f4193)

As you can see, the Authorization header is automatically removed on our error case, as opposed to the OK case where everything is working as intended. Both set of screens were taken on the same environment, with the only diference being the browsers and its version (both being chromium am I right ?)
Thanks in advance for reading and for any help :visage_légèrement_souriant: !

**Comment by RLSilveira** [comment]
I have the same issue after upgrading Microsoft Edge to version 119.0.2151.44.

**Comment by brunomendeslima** [comment]
I'm experiencing this issue in Chrome Version 119.0.6045.106.

**Comment by golfyos** [comment]
I'm facing this issue as well after upgrading Chrome to the latest version (119.0.6045.105)

Authorization header is always missing.

I'm using Requestly via Chrome extension.

**Comment by sachinjain024** [comment]
Thank you @laurent-inqom @golfyos @RLSilveira @golfyos for informing us about this issue. This looks like a recent change from the Chrome side. 

We will follow up with the Chrome team about this. In the meantime, here is a work around :-

1. Create a new HTTP Rule
2. Select Modify HTTP Headers
3. Add Request Header - Authorization and value should be copied from your other API request
4. Save the Rule

I have created a SharedList for you here - https://app.requestly.io/rules#sharedList/1699438081127-Add-Authorization-to-localhost

I know it is not convenient (as it used to be earlier) but this should fix the issue for you temporarily.

<img width="840" alt="image" src="https://github.com/requestly/requestly/assets/3108399/55ebae37-4764-4df1-89ae-ab3d174e635d">

**Comment by sachinjain024** [comment]
We don't see anything suspicious in the Chrome 119 change log - https://developer.chrome.com/blog/new-in-devtools-119/ as well.

**Comment by alphafast** [comment]
FYI, I work around by install an older version. It works as normal (I install version 117.0.5938.89)

**Comment by sagarsoni7** [comment]
Chrome Enterprise [release notes](https://support.google.com/chrome/a/answer/7679408?sjid=2334110632176692414-AP#chromeBrsrK119) mentions this

> Remove Authorization header upon cross-origin redirect back to top
> 
> The [Fetch](https://fetch.spec.whatwg.org/) standard has been updated to remove Authorization header on cross origin redirects. Chrome 119 implements this change to the specification. Prior to Chrome 119, when a cross origin redirect, such as from foo.test to bar.test, happened with an Authorization header, Chrome preserved the Authorization header and bar.test could receive the header. Starting Chrome 119, Chrome removes Authorization headers when cross origin redirects happen, meaning that bar.test no longer receives the Authorization header.
> 
> Chrome 119 on ChromeOS, Windows, Mac, Linux, Android

**Comment by sachinjain024** [comment]
I have created a simple Loom Video describing the issue - https://www.loom.com/share/f3af3e10154a4c9dae296dd3b7b62ea1

## Steps to reproduce
1. Install Requestly
2. Import - https://app.requestly.io/rules#sharedList/1699448492370-Echo-Headers-from-Redirected-request
3. Open API Client - https://app.requestly.io/api-client and Hit www.example.com

In Chrome v118 Authorization header is being passed while in Chrome v119 Authorization header is not passed.

**Comment by sachinjain024** [comment]
> Chrome Enterprise [release notes](https://support.google.com/chrome/a/answer/7679408?sjid=2334110632176692414-AP#chromeBrsrK119) mentions this
> 
> > Remove Authorization header upon cross-origin redirect back to top
> > The [Fetch](https://fetch.spec.whatwg.org/) standard has been updated to remove Authorization header on cross origin redirects. Chrome 119 implements this change to the specification. Prior to Chrome 119, when a cross origin redirect, such as from foo.test to bar.test, happened with an Authorization header, Chrome preserved the Authorization header and bar.test could receive the header. Starting Chrome 119, Chrome removes Authorization headers when cross origin redirects happen, meaning that bar.test no longer receives the Authorization header.
> > Chrome 119 on ChromeOS, Windows, Mac, Linux, Android

@sagarsoni7 In this case, this is by design. We should check with the Chrome Extension team on how to handle this. Let me initiate this.

**Comment by Sheikh566** [comment]
Any idea when this fix will be live? @sachinjain024

**Comment by nafees87n** [comment]
Hey @Sheikh566 
We have released a fix for this. We'll notify you once the new version is available in the chrome store.

**Comment by sachinjain024** [comment]
We made a fix for this issue but it caused a regression (See Issue #1269) and that's why we had to revert the fix for this issue. This is still in progress and we will make another release with the fix of this issue.

**Comment by nafees87n** [comment]
🚀 We have released the fix in `v24.1.3`. Make sure to update the extension.

**Comment by Sheikh566** [comment]
Using the latest version of Chrome, Firefox, and Requestly. But the header is still not forwarded.

**Comment by golfyos** [comment]
It's still not working. The header is not being forwarded as it was previously.

**Chrome version:** v120.0.6099.129 (Official Build) (arm64)
**Requestly version:** v24.1.3

**Comment by nafees87n** [comment]
Hi @Sheikh566 @golfyos 
Do you still get 401 error? Can you please share the logs and rule you are using?

**Comment by golfyos** [comment]
@nafees87n 

rule:
![Screenshot 2567-01-06 at 15 24 28](https://github.com/requestly/requestly/assets/21194352/bbd8bea8-ce5c-4e46-9875-267232da0a75)

the request header when the rule is active
![image](https://github.com/requestly/requestly/assets/21194352/d5e82bc4-fb13-4dd1-a8f5-e2af8c6c03bf)

the partial request header when the rule is not active
![image](https://github.com/requestly/requestly/assets/21194352/896a559f-3c88-4be5-8cb2-dc10c48c76c4)

response:
![Screenshot 2567-01-06 at 15 23 21](https://github.com/requestly/requestly/assets/21194352/9850597b-ab72-4fd7-88da-454ff437cba2)

my server log:
`UnauthorizedError: Authorization required in header payload.`

**Comment by nafees87n** [comment]
@golfyos Can you please invoke the same fetch request (when the rule is active) once again after the page has loaded? I want to check if we have any race condition when the scripts are loaded and when the fetch request is fired.

**Comment by golfyos** [comment]
@nafees87n  I've tried invoking the same fetch request after the page has loaded. Still not working

**Comment by Postremus** [comment]
@golfyos Any update? FTR. Authorization Header is still not forwarded.

**Comment by sachinjain024** [comment]
Thanks, @Postremus, for bumping this up. We will investigate what could be happening here. Could you share a website where we can replicate this?

**Comment by nafees87n** [comment]
Hi
If anyone is available for a quick call to help us debug this issue, it would really help us in resolving it.
You can use this [link](https://cal.com/nafees-nehar/15min) to schedule a call with me.
Thank you.

**Comment by nafees87n** [comment]
Thanks @Postremus and @Sheikh566 for joining the call. It helped us identify the issue. We wouldn't have been able to do it without your help. 
It seems that `Authorization` header is not forward in case of `XHR` cross origin redirects as well. We will fix this in the next release.

**Comment by Postremus** [comment]
@nafees87n Any update on getting this fix released?

**Comment by nafees87n** [comment]
Hey @Postremus 
Currently, we have our last release rolled out partially. Once that is released to 100% users, we plan to release this fix for all users by Friday.

**Comment by gerardog** [comment]
Awesome tool guys! please comment when this fix will be available! I am using the desktop version.

**Comment by Postremus** [comment]
Any updates? I am on version "24.2.17" of the chrome extension, still getting a 401.

**Comment by nafees87n** [comment]
Hey @Postremus 
The fix will be released in v24.3.5
We'll notify once it is available in the chrome store

**Comment by sachinjain024** [comment]
We have rolled out this in v24.3.5, which is at the 50% rollout stage. If no issues are reported further, we will make a 100% rollout by tomorrow.

**Comment by totoberg123** [comment]
@nafees87n  @sachinjain024 I am having the same issue on the Desktop App (Windows 11). I am logging traffic using the built-in proxy server. When using a Redirect or Modify URL Rule the 'Authorization' header is not being passed.

**Comment by Postremus** [comment]
I can confirm I am no longer getting the 401 with  v24.3.5

**Comment by nafees87n** [comment]
Thanks for the confirmation @Postremus . Glad to know that it works

**Comment by sachinjain024** [comment]
This has been rolled out to 100% now.

**Comment by sachinjain024** [comment]
> @nafees87n @sachinjain024 I am having the same issue on the Desktop App (Windows 11). I am logging traffic using the built-in proxy server. When using a Redirect or Modify URL Rule the 'Authorization' header is not being passed.
> 
> Edit: I created an issue: [requestly/requestly-desktop-app#71](https://github.com/requestly/requestly-desktop-app/issues/71)

Thanks for reporting this. We will pick this up soon in the upcoming week. cc @nsrCodes

**Comment by sachinjain024** [comment]
Closing this issue as this has been rolled out completely. We will work on separate ticket for solving this in the desktop app.

**Comment by nafees87n** [comment]
Hey @vitolrosario 
What error are you getting?

This issue is about `authorization` header not getting forwarded in case of cross-origin redirects using Requestly redirect rule. Feel free to open a new issue [here](https://github.com/requestly/requestly/issues/new/choose) if you are encountering any issue.

**Comment by LeopoldLerch** [comment]
Have still this issue. 
In the chrome-plugin, it does work a long time. However, obviously if many requests are done, at some point it stops and the rest of the requests return in 401 again. reloading the page, and it seems to be reset.
