### ISSUE TITLE
bug: Certificate Invalid in MacOS Sonoma when using System Proxy settings

### ISSUE THREAD

**Issue by StefanWrightGlassbox** [requestly/requestly#1225]
### Describe your issue?

When I set the system proxy settings to go via Requestly and then load an HTTPS site in Chrome (seen in Safari too) I get a warning that the certificate authority is invalid. I am sure this never used to happen before Sonoma install. I have ensured that the RQProxyCA is trusted in Keychain and it's got a valid until date of Noevmber 2024 so it's definitely in date

### Repro steps

1. Open Requestly
2. Open the MacOS Proxy settings
3. Set proxy to go via Requestly
4. Open chrome (NOT via requestly)
5. go to any HTTPS site
6. You'll get a warning that the authority is invalid

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS Sonoma

### Requestly Version

v1.5.12

**Comment by nsrCodes** [comment]
Hey @StefanWrightGlassbox thanks for pointing this out. We have just released a fix for this. Can you please try the latest version of the desktop app and let us know if it works for you now.

**Comment by StefanWrightGlassbox** [comment]
Hey @nsrCodes 

if I try to get to certain sites (github included) I will still get warnings regarding HSTS or invalid certificates :( I don't think it's fully completed as yet

**Comment by nsrCodes** [comment]
Hey @StefanWrightGlassbox I think we missed a few edge cases, we have made another release that now let's you manually regenerate the ssl certificates for the proxy. Can you please update the app and follow the steps mentioned here and let us know if it works
https://developers.requestly.io/troubleshoot/untrusted-certificate/

**Comment by StefanWrightGlassbox** [comment]
@nsrCodes Thanks for that, I did that and it worked. It might be worth mentioning users need to go to "Connect Apps" to reapprove the certificate into Keychain, I had tried just opening Requestly and then going and setting the proxy on MacOS settings which made no difference. I had to try launch one of the apps within Requestly to approve the new cert

**Comment by sagarsoni7** [comment]
Thanks @StefanWrightGlassbox ! We're updating the instructions in the UI.
Please feel free to reopen in case if the issue appears again.
