### ISSUE TITLE
bug: Desktop app causes screenshots in clipboard to fail to upload

### ISSUE THREAD

**Issue by jpaddock** [requestly/requestly#1880]
### Describe your issue?

When the desktop proxy is running, you can't upload images that are from your clipboard.  For example, pasting an image from the clipboard to Gmail compose window returns a 200OK for https://mail.google.com/_/upload.  If you have Requestly running though, Google returns a 400 Bad Request.  Same issue for Slack.

### Repro steps

1. Open Requestly Desktop on Mac OS.
2. Take a screenshot and capture in clipboard with a tool like Monosnap.
3. Paste the image into Gmail or Slack.
4. You'll get an error or a binary file is uploaded that can't be viewed.
5. Close the Requestly app.
6. Paste the image into Gmail or Slack again.
7. Now the image uploads as it should.

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Mac OS 14.5 (23F79) Apple M3 Pro

### Requestly Version

1.6.0

**Comment by nsrCodes** [comment]
Hey @jpaddock thanks for reporting this.

We have fixed the upload issue for slack. Please make sure you are on the latest version to get the fix (v1.6.1) or download it from [here](https://github.com/requestly/requestly-desktop-app/releases/download/v1.6.1/Requestly-1.6.1-arm64.dmg)

We haven't been able to figure why exactly it breaks for gmail. One guess is that the site heavily relies on h3, while our proxy runs on http1.1 (_but google drive uploads do no break, even though it also relies on h3, hence this is a guess_)

**Comment by jpaddock** [comment]
Thanks for fixing slack, but Gmail is critical for me. Please let me know
when you figure this out.

**Comment by erquhart** [comment]
This is still happening, running system wide on Mac. screenshot pngs upload as binary, movies also won't upload and play, likely for the same reason. Some sites stopped loading correctly also, and Apple started prompting that it couldn't connect to my Apple account. Turning system-wide off fixes everything.

**Comment by Ronakkadhi** [comment]
Closing as stale — no activity for over a year.

As part of the 2026 repository restructure, we're closing dormant issues to focus on actively-tracked items. If this is still relevant, please re-open or file a fresh issue at the right home:

- 🌐 **HTTP Interceptor** (Chrome extension + web app + desktop proxy) → [requestly/interceptor](https://github.com/requestly/interceptor/issues/new/choose)
- 🚀 **Requestly API Client** → this repo

Thanks for taking the time to file the original report.

**Comment by Ronakkadhi** [comment]
Reopening — reverting the bulk-close while we test the migration flow on a smaller sample first. Sorry for the inbox noise.
