### ISSUE TITLE
bug: Requestly conflicted with TP-Link Web Interface

### ISSUE THREAD

**Issue by michioxd** [requestly/requestly#1923]
### Describe your issue?

After I installed Requestly, I could not access the TP-Link Router Web Interface.

### Repro steps

1. Install Requestly
2. Access [TP-Link Router Web Interface](https://emulator.tp-link.com/webpages_BE900_20230404/) ([you can pick another demo in there](https://www.tp-link.com/us/support/emulator/))

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Google Chrome 126.0.6478.127 (Official Build) (Windows 64-bit)

### Requestly Version

24.6.21 (MV3)

### Error screenshot

The website returned below:

![image](https://github.com/requestly/requestly/assets/80969068/1c6664e8-7e90-4b9e-971f-840e6b72a3d4)

**Comment by sachinjain024** [comment]
Thanks @michioxd for creating this issue. We have released a new version today, the build is uploaded to Chrome Store. As soon as google approves it, we will update it here.

Most likely this issue will get resolved in the latest version.

**Comment by michioxd** [comment]
> Thanks @michioxd for creating this issue. We have released a new version today, the build is uploaded to Chrome Store. As soon as google approves it, we will update it here.
> 
> Most likely this issue will get resolved in the latest version.

Thanks for your reply. I have updated to version `24.7.2` but it seems this problem still occurred. And it conflicted with [HoyoLab](https://www.hoyolab.com/) website too after I click Login button.

![image](https://github.com/requestly/requestly/assets/80969068/d6250450-c0d9-4423-abed-5c86dc54081e)

**Comment by wrongsahil** [comment]
v24.7.7 is available in the chrome store now. @michioxd Can you please manually update the extension using these [steps ](https://developers.requestly.com/guides/update-requestly-extension/)

**Comment by michioxd** [comment]
> v24.7.7 is available in the chrome store now. @michioxd Can you please manually update the extension using these [steps ](https://developers.requestly.com/guides/update-requestly-extension/)

Nice work, it's now working 😊.
