### ISSUE TITLE
pinned rules disappear randomly

### ISSUE THREAD

**Issue by coreyb-cbs** [requestly/requestly#205]
## Expected Behavior
The rules I pin should stay pinned until I unpin them. When I click on the Requestly icon in the extension toolbar I should see my pinned rules. When I click on the "open app" button I see that my previously-pinned items are also unpinned in the "[my rules](https://app.requestly.io/rules/my-rules)" page.

## Current Behavior
Pinned items disappear randomly. Sometimes they disappear within an hour, sometimes they disappear in a few days. All previously-pinned rules become unpinned.

## Your Environment
- Operating System and version : Chrome 100.0.4896.75 on Mac OSX 10.14.6
- Extension Version : 22.5.13
- Desktop App Version :

**Comment by sachinjain024** [comment]
@coreyb-cbs Confirming this is a bug. Clicking on the pin icon is not persisting the rule state. We will fix this bug on priority. Thanks for helping with the steps.

**Comment by lazyvab** [comment]
This issue is already fixed in branch. It will rollout in production soon.

**Comment by sachinjain024** [comment]
@sagarsoni7 The issue still persists. Can you please have a look at this on priority?

**Comment by sagarsoni7** [comment]
Just deployed an update, this issue should now be resolved. Please reopen if still persists

**Comment by coreyb-cbs** [comment]
I was just able to reproduce this issue. When I added a new rule and pinned it, that was the only pinned rule - the previously pinned rules were unpinned.

**Comment by sagarsoni7** [comment]
Thanks @coreyb-cbs, I'll resolve this on priority

**Comment by sagarsoni7** [comment]
We deployed a fix few days ago. Please let me know in case you still face this issue.

**Comment by sachinjain024** [comment]
Hey @coreyb-cbs Could you please confirm if things are running fine at your end?

**Comment by coreyb-cbs** [comment]
@sachinjain024 Apologies for the delay, I was on holiday. I just checked and had no pinned items. I re-pinned several rules and will check back periodically over the next 24-48hrs to see if they persist.

**Comment by lazyvab** [comment]
Hi @coreyb-cbs, did you face the issue again? If not, can we please close the issue?

**Comment by coreyb-cbs** [comment]
so far so good!
